### ISSUE TITLE
Pink Bar on Mention Confusing and Odd

### ISSUE THREAD

**Issue by rklados** [dubtrack/www-dubtrack-fm#100]
When a user is mentioned there's a pink bar that's added to the right side of the chat box, which expands past the mention if a user continues to speak.  Some users have mentioned confusing this as the scrollbar.

It doesn't seem very necessary since the mentioned user is already bright pink, and it makes chat look odd and confusing. Could this be removed?

**Comment by WiBla** [comment]
Knowing when you have been mentioned is really helpful, I do not think it should be removed, but re-worked, On my script, when people are getting mentioned, the whole text is gonna be highlighted, not just only a bright bar on the right. But after all it's just a matter of personal preferences..
Also, do remember that they are adding a bunch of feature to test them, they do take count of user feedback so it is very much likely to change.

**Comment by rklados** [comment]
Since the name already turns bright pink, so it's already noticeable feedback. It's good too, since this is how many other chat services work (IRC, plug, etc).

Of course preferences are good, but this part of it is actually confusing. Pink bar looks like it should be the scroll bar, and if a user clicks on it, can accidentally hide chat. 

This also doesn't function correctly, since it spans the entire list item of the chat, which can grow long past the mention itself.

**Comment by nambok** [comment]
yeah agreed the bar on the side is a bit confusing will remove that later today

**Comment by rklados** [comment]
Soooo much better. Thanks!
