### ISSUE TITLE
Bracket at end of url's posted in chat not included in hyperlink

### ISSUE THREAD

**Issue by ghost** [dubtrack/www-dubtrack-fm#106]
ie:
' https://en.wikipedia.org/wiki/Kok_(surname) ' will not include the closing bracket, and will instead only include ' https://en.wikipedia.org/wiki/Kok_(surname '  as the url

for reference, 
' http://www.notareallink.com/test() ' will only include ' http://www.notareallink.com/test '
and
' http://www.notareallink.com/test(test) '  will only include 'http://www.notareallink.com/test(test '

**Comment by swordling** [comment]
I fixed this in my latest pull request. It should be added to the site soon.

**Comment by ghost** [comment]
dank
