### ISSUE TITLE
Animated gif in chat are not always displayed

### ISSUE THREAD

**Issue by jsmoro** [dubtrack/www-dubtrack-fm#109]
here is an example:
https://media.giphy.com/media/3o85xCFkxSNBe4gfgA/giphy.gif => displayed
http://i.giphy.com/3o85xCFkxSNBe4gfgA.gif => not displayed

**Comment by Leykis** [comment]
I believe this is due to the domain "giphy.com" not being whitelisted here : https://github.com/dubtrack/www-dubtrack-fm/blob/staging/public/assets/js/dubtrack/src/config.js#L686

**Comment by jsmoro** [comment]
no more restriction on gif providers, nice :+1:
