### ISSUE TITLE
Hide in-line images

### ISSUE THREAD

**Issue by scytheria1001** [dubtrack/www-dubtrack-fm#11]
We should be able to close or hide in-line images on an individual basis. There's nothing to prevent a user from pasting something NSFW or otherwise offensive into the chat, then the only way to get rid of it is to spam it up to the top of the page.

**Comment by rklados** [comment]
+1 :)

**Comment by chrisrohn** [comment]
i'd like to have a user setting to turn them off completely and just show the link - i cant have photos popping up all the time on my screen at work.

**Comment by coryshaw1** [comment]
I think a click to expand would be good rather than opening the link in a new tab.

As for the NSFW aspect, maybe mods and higher users have the ability to flag the image as NSFW to add a warning next to the link. In user settings, people can choose whether or not to mark any NSFW links/images.

**Comment by chrisrohn** [comment]
this is getting pretty urgent.  a number of trolls have come through posting porn in chat today and the only way to combat it is to flood the chat.
