### ISSUE TITLE
Display the number of "guests" currently listening to a room

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#111]
Anyone can listen in and read the chat of dubtrack's communities, which is great - but we should also be able to see how many "guests" are listening in. Please provide an indicator that tells us. Thanks!

**Comment by NathanZepol** [comment]
+1 
Would also be great to see a public/private option for each room that is change-able by the owner.

**Comment by WiBla** [comment]
:+1:

**Comment by Leykis** [comment]
+1
Would also be great to see a public/private option for each room that is change-able by the owner.

**Comment by RobGoldy** [comment]
+1

**Comment by Larry1123** [comment]
This is a thing!
