### ISSUE TITLE
the /skip command should include the songid

### ISSUE THREAD

**Issue by japerry** [dubtrack/www-dubtrack-fm#113]
When the network and everything is great, a /skip will skip the song that you're expecting: the currently playing song.

But what about when the network is lagging, or people try to skip as a debugging measure because a song is stuck? Currently if your skip doesn't go through the network quick enough, and the current song ends, then skip will work on the next song.

Plug.dj attached a historyID to the /skip (or skip button) command so that only the current song would get skipped. If you click skip and its too late, it wouldn't skip the next song because the historyID wouldn't match.

**Comment by netux** [comment]
+1 once a mod was lagging and accidently skipped two songs at once.

**Comment by RobGoldy** [comment]
+1 an easy fix for this would be to have a 5 second cool-down period for /skip at the beginning of new tracks.

**Comment by joedubtrack** [comment]
This has been completed.
