### ISSUE TITLE
Follow option not appearing in people's profiles.

### ISSUE THREAD

**Issue by GrimT94** [dubtrack/www-dubtrack-fm#12]
The follow button doesn't appear in people's profiles, I tried refreshing and restarting, still has no effect, plus tried with all addons/extensions disabled no fix. (logged with existing twitter account) - dont know if thats the problem..

![k88mlqh](https://cloud.githubusercontent.com/assets/14843863/10113591/ee34053c-63dd-11e5-81e8-18e94cb816bd.png)

http://i.imgur.com/k88mLqh.png

Account name: tony

**Comment by Leykis** [comment]
This option is showing up for me on the "tony" account. May want to check again, might have been fixed?

**Comment by GrimT94** [comment]
It got fixed thanks
