### ISSUE TITLE
impossible to add a song recently played to room queue

### ISSUE THREAD

**Issue by jsmoro** [dubtrack/www-dubtrack-fm#122]
When adding a song a song recently played in room queue we get the following message:
"song already in queue"

**Comment by netux** [comment]
As far as I know, this is a Dubtrack thing that prevents people to play songs that have been played in the last hour.

**Comment by nambok** [comment]
@jsmoro we are currently working on the redesign, but this will be an option per room :)

**Comment by jsmoro** [comment]
ok, thank you for the replies
keep up the good work! ;)

**Comment by RobGoldy** [comment]
I actually really like this as is. An easy get-around for this is to just get different versions of the same song but honestly if you are playing literally the same video multiple times within the same hour that says a lot....

**Comment by Larry1123** [comment]
No longer valid.
