### ISSUE TITLE
Editable track names

### ISSUE THREAD

**Issue by invisibletank** [dubtrack/www-dubtrack-fm#123]
It would be nice to be able to edit track names when adding to the queue or to a playlist.  This would come in useful for tracks where the artist does not list their artist name in the song title.  It would also be useful for promoters and artists to switch the name to ID - ID when they don't want to give away who wrote the song in case it is not finished, or they are trying to get a reaction from the room without the artist name influencing the reaction.

Here is more on the reasons for ID - ID: https://www.facebook.com/notes/max-graham/why-are-songs-titled-as-id/10151178583559075

**Comment by ronaldb** [comment]
Seconded. If only to fix the Artist - Title. I may be a little OCD, but it irks me when the name of the song or the artist is spelled wrong.. :-)

**Comment by CypherNL** [comment]
Support, i need this so i don't need to edit the titles in the scrobbler i use for the site.

**Comment by RobGoldy** [comment]
This has already been requested. Please see #7
