### ISSUE TITLE
Rotating songs in playlist

### ISSUE THREAD

**Issue by invisibletank** [dubtrack/www-dubtrack-fm#124]
It seems currently if I queue a playlist, the top of the playlist will always play first.  So if I play through half of my playlist one day, then come back the next day and queue up, the same songs will be played again, with the songs at the bottom taking a long time to be played.

It would be great to have a song in your playlist automatically be moved to the bottom of the playlist once it has been played.

**Comment by ronaldb** [comment]
I think this will be a tough one, since you can copy your playlist to your current queue, and then add songs to your current queue, or move them around, without touching the playlist that you copied from.

What I do to circumvent this, is shuffle my playlist, before I add it to my queue.

**Comment by RobGoldy** [comment]
Yeah, just press the shuffle button. What would be really nice is a "Shuffle Que" button.

**Comment by joedubtrack** [comment]
We added a shuffle to "My Queue". Closing this. Feel free to reopen if you have another suggestion
