### ISSUE TITLE
Ability to see how many grabs (<3) a song has received

### ISSUE THREAD

**Issue by scytheria1001** [dubtrack/www-dubtrack-fm#13]
Would be nice to see how many users have added a song that's playing to their own playlist

**Comment by rklados** [comment]
+1 - is this what do? +1?  

We're working on a bookmarklet for this type of thing, a browser event would be awesome to bind to.

**Comment by nambok** [comment]
awesome and yeah +1 is always good :), once I have created the event I'll let you guys know
