### ISSUE TITLE
In playlist popup screen, queue items should be always visible

### ISSUE THREAD

**Issue by jsmoro** [dubtrack/www-dubtrack-fm#132]
**_with new display only (24/10/2015)**_

With many playlist created, when you scroll to the bottom of the lists, the queue menus are not displayed  ("My Queue", "Room queue", "Room History")

The scroll position is kept when the playlist  popup is closed/reopened.
It can be confusing for novice users to search these features.

**Comment by Larry1123** [comment]
Reopen if you think it should be.
