### ISSUE TITLE
Mobile functionality

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#135]
The relaunch of the site eliminated mobile functionality.  Please restore this as soon as possible - for me, this was the most exciting and useful part of the previous design.

Now I have to look at this:

![oou2osd](https://cloud.githubusercontent.com/assets/11859955/10731437/d181dba2-7bcb-11e5-9f11-f5e478fb9c8a.png)

:\

**Comment by nambok** [comment]
we've rolled back in the mean time, based on the feedback we will sort everything out

**Comment by rklados** [comment]
+1 - The mini-mode/mobile-mode with the tabs for Video/Chat/Users was a pretty impressive feature that a lot of us ended up relying on for use at work and on the road.

**Comment by joedubtrack** [comment]
Redesign is mobile responsive now. Closing.
