### ISSUE TITLE
Private Messaging bug

### ISSUE THREAD

**Issue by djfc** [dubtrack/www-dubtrack-fm#136]
Over lap issues within the Private Messaging when trying to select a user to message.
 (see attached screenshot) 
![screen shot 2015-10-26 at 11 08 31 am](https://cloud.githubusercontent.com/assets/15222720/10732930/c3c18ff6-7bd2-11e5-9b39-60b00eed907e.png)

**Comment by Not-Kris** [comment]
It's because the search results background is transparent. I added this to custom css to fix it: 

```
#main-message-list .search-results {
    background: #1c1c1c;
    border: 1px solid #333;
}
```

**Comment by nambok** [comment]
this was fixed already :)
