### ISSUE TITLE
[Feature request] Make use of the useless(?) Video button

### ISSUE THREAD

**Issue by Not-Kris** [dubtrack/www-dubtrack-fm#137]
The video button currently does nothing, while it could be used as a toggle to hide the video instead of having a new button for that (NSFW). The NSFW button could then be made into a skip button since having that below the video creates clutter and makes it too easy to accidentally hit.
In short:
"Video" -> "NSFW"
"NSFW" -> "Skip"
![image](https://cloud.githubusercontent.com/assets/12618255/10733304/84cc3a2c-7bfe-11e5-9495-50f0cc7e1cf6.png)

**Comment by chrisrohn** [comment]
I like this.  Actually, I thought the NSFW button was an owner flag option for the room in case you wanted to play nsfw videos. If all that button does is turn the video on and off then I say get rid of it.

**Comment by joedubtrack** [comment]
NSFW Changed to skip. Added hide video in different location.
