### ISSUE TITLE
[Bug] If you delete a message, new messages are appended to the deleted one and can't be deleted

### ISSUE THREAD

**Issue by Not-Kris** [dubtrack/www-dubtrack-fm#138]
If you delete a message, and that same person sends a message again before other messages are posted, the new messages can't be deleted because they're appended to the deleted message. 
![image](https://cloud.githubusercontent.com/assets/12618255/10754535/9c746254-7c98-11e5-9634-e169de049988.png)
Notice how there's no delete button.

**Comment by anjanms** [comment]
+1

Wanted to enable our bot's anti-spam. But found it fails to work properly because of this.

**Comment by Larry1123** [comment]
This is fixed! :)
