### ISSUE TITLE
[Feature Request] Pull SoundCloud album art and show it while playing

### ISSUE THREAD

**Issue by FranciscoG** [dubtrack/www-dubtrack-fm#140]
when playing a song off of soundcloud,  use the album art (if it exists) instead of a generic DT logo.  I know it exists in their API.

**Comment by chrisrohn** [comment]
I wish plug had done this, and I would like it if dubtrack did this, too.  The main argument against it is that image quality isnt always the best, but I don't think it's that big of a deal and would be better than seeing the secondary (primary? i'm still baffled over the two different logos) dubtrack logo on the screen.

**Comment by swordling** [comment]
I began working on this myself and the results aren't pretty: http://prntscr.com/91jsso. I even tried making the image centre itself as a 128px*128px size but you could still see the pixels. :crying_cat_face:

**Comment by swordling** [comment]
Disregard, I figured out changing -large to -original on the end of the URL loads a high-res version of the artwork.

**Comment by coryshaw1** [comment]
@swordling There's also a -t500x500 version, and a -crop version that is 400x400

**Comment by FranciscoG** [comment]
Since the images are square what about centering it in the video window instead of stretching it to fit it?  Just put black space or maybe an interesting pattern in the background?

**Comment by Larry1123** [comment]
This is a thing!
