### ISSUE TITLE
Show next song above progress

### ISSUE THREAD

**Issue by Hebgbs** [dubtrack/www-dubtrack-fm#141]
It would be nice for moderators and users alike to see what is at the top of the room queue, and it can be presented as an element that has the present song, then the next song in the same div sliding up and down. Show it maybe once every 50 seconds for 10 seconds.

If you wanted to make it extra-fancy, have an animation slide the next song away in the same direction, reset at 0 and move the present song back into view.

**Comment by swordling** [comment]
It's already accessible to anyone who wants to see it in the room queue menu. But I don't really like this feature and something similar was suggested for plug.dj. But user feedback was very bad, even from mods, because people didn't like the idea that others could steal their songs and/or the surprise of their song could be ruined. 

It also takes excitement and humour out of the room in my opinion. A troll song is nice every now and then.

**Comment by japerry** [comment]
Also -1 on this. If it were to be implemented, I'd strongly want to turn it off in my room. We like the surprise.

**Comment by seatsea** [comment]
I agree but it would be nice if there could still be some sort of ETA
system to replace it if it's removed.

**Comment by RobGoldy** [comment]
I actually do not see the relevance of a "surprise track" and I think this would be a cool feature if implemented correctly.

**Comment by chrisrohn** [comment]
@RobGoldy the best example I can think of is the "Connect The Songs" room where the thrill is finding out what the connection is once a song starts playing.  If you already know the next song, the point of the room is ruined.

But I do think the "queue a song" button with the turn indicator would be better suited to telling the you the individual user, not the room, what your personal next song is so you can make a change if you want.  As it is now, seeing "queue a song" all the time confuses the user into thinking nothing is currently queued up.

**Comment by Larry1123** [comment]
I don't feel that this would be a good thing to add to dubtrack itself. Likely something that a plugin would be good for doing.
