### ISSUE TITLE
New UI: Make "Queue a song" also pause and resume queue

### ISSUE THREAD

**Issue by Hebgbs** [dubtrack/www-dubtrack-fm#143]
A simple-enough request; Make the "Queue a song" button multi-functional with the following conditions;
If playing music, show "Skip song" (with tooltip on hover saying "Quit playing this song" or similar)
-- If room moderator, show the "Skip song" button underneath or next to the global action button always
-- If the last song in queue is playing, have it also remove user from queue
If not playing and more than one song, show "Pause queue" (with tooltip on hover saying "Quit playing music" or similar)
If paused, show "Resume queue" (with tooltip on hover saying "Play music" or similar)
All else, show "Queue a song" and invoke media browser on active.

**Comment by tris90190** [comment]
Sorry Thats not what dubtrack is.

**Comment by swordling** [comment]
Yes it is.

**Comment by Larry1123** [comment]
I don't think that this is still valid. Reopen if you feel otherwise.
