### ISSUE TITLE
[Feature Request] Scrolling Comments on Video

### ISSUE THREAD

**Issue by SukaNekoto** [dubtrack/www-dubtrack-fm#144]
Being used to Nsen (Niconico Douga's equivalent of this kind of website), it bothers me when I don't see the comments scrolling on the video. It's a pretty fun feature I think; you can change the color of the comments and put it on the top and bottom of the video and to me it makes it easier to see the comments sometimes. There's also an option to turn off this feature for those who just want to enjoy the video as is.

The comments scroll from right to left, the first comment is always on the top of the other scrolling comments. If you choose the option for the comment to be on top or bottom of the video, it will stay there for about 10-15 seconds before disappearing and the size of the comment will shrink depending on how much text. The comments which are set to "top" will stack on top of each other while the ones which are set to "bottom" will stack below.

Here is a screenshot of Nsen. My comment is the one with the yellow outline.
![nsen image](http://i1167.photobucket.com/albums/q636/SukaKitty/nsenscreen01.png)

And here is an edit of a dubtrack screenshot I made to give an idea of what I mean. The comment on the bottom is to show what it would be like if one were to select the "bottom" option. As well, if one were to put a picture and text at the same time, the text would shrink to a certain size, much like when ascii is pasted into an Nsen comment. I figured putting the avatar next to the comment would be enough to identify who is the one speaking.
![dubtrack with scrolling comments](http://i1167.photobucket.com/albums/q636/SukaKitty/dubtrackscrollingcomment.png)

**Comment by RobGoldy** [comment]
i don't like this and didn't like the comment system that dubtrack used previously because a lot of people can curse or make malicious comments that stick with videos for all to see

**Comment by SukaNekoto** [comment]
Why don't you like it? It's not like these are going to be permanently on the video; just for a few seconds and disappear forever. If it's malicious words, it's going to be even more temporarily seen than it would be in the chat as the comments flow right to left for a couple seconds.

**Comment by RobGoldy** [comment]
Ah I see @SukaNekoto . I like your idea and that makes sense. The way the comment system used to work is that they were permanent and they stayed across all rooms. If implemented correctly this could be really cool, but I have to admit I dislike the idea of overlaying it on top of the video. I can imagine how distracting comments on a video must be in a massive room if you actually want to watch the video. It might be easier to have a comment box (with temporary comments like you are talking about) below the video so that it doesn't take away from the video.

**Comment by swordling** [comment]
I'm not a huge fan. It will allow people to put irrelevant things on the video and also be distracting as well as resource intensive is someone decides to put upload a HD gif, or a large amount of text - not to mention the animations that appears to go with it. In the service you showed above it doesn't look like they have a chat (commenting on a video is how they chat). Dubtrack of course already has a chat too, it seems silly to have to communicate on the video, the way I see it if you have something to say about the video say it in the chat where the video isn't disrupted. 

Just my thoughts, but that's not to say it's a bad idea. :)

**Comment by nambok** [comment]
yeah looks like this could get a bit messy. It doesn't mean you can't have this thou, this could be a great idea for a plugin since seems hit or miss depending on the user.

Let me know if you need help getting started
