### ISSUE TITLE
"ghosting" of users

### ISSUE THREAD

**Issue by rklados** [dubtrack/www-dubtrack-fm#15]
It seems like users end up sticking around, after they've logged off or closed the window.  We made a user join/leave dealio where it should show leaves and joins, but it doesn't seem accurate.

Our room info also doesn't seem accurate. Some people close the browser and come back later to realize their avatars have been there, the entire time.  Room occupancy numbers seem inaccurate.

**Comment by zewm** [comment]
I'll second this issue. I'm seeing the same thing on my end. I've had the same 3 users in my room since the first day they joined.

**Comment by nambok** [comment]
this is now fixed :), feel free to reopen if anything
