### ISSUE TITLE
[Feature Request] Allow Mods to Remove Songs From Room's Que.

### ISSUE THREAD

**Issue by RobGoldy** [dubtrack/www-dubtrack-fm#154]
This request comes from emerald (Owner of Trance House Chill).

A creator does not have permission to delete a song from the room queue. Mods of any kind probably should be able to.

**Comment by RobGoldy** [comment]
This actually already exists.

**Comment by emeraldTHC** [comment]
The bug still persists.  I am the creator of the room and here is what I am seeing when I try to delete a song from the room queue (attached screenshot)
![dt-bug1](https://cloud.githubusercontent.com/assets/15715453/11020665/f98f657e-85f3-11e5-9538-e83db6936310.png)

**Comment by RobGoldy** [comment]
Moved to #156 Thanks for creating an account and making your own post to follow up with this!

**Comment by nambok** [comment]
@emeraldTHC what times are you usually in your room? Ill come by tomorrow and have this sorted for you
