### ISSUE TITLE
Creator of room does not have permission to delete song from room queue

### ISSUE THREAD

**Issue by emeraldTHC** [dubtrack/www-dubtrack-fm#156]
Hi. I am the creator of [Trance House Chill] but I lack the permissions to delete a song from the room queue. I have managers who say they can do it, but I'm unsure if other mods can. (I think all mods of all ranks should be able to) but I definitely cannot. Attached is a screenshot to show what I am seeing. (Thank you all for the incredible work on DT it is wonderful and showing great improvement already!) 

![dt-bug1](https://cloud.githubusercontent.com/assets/15715453/11020689/b4733910-85f4-11e5-9b6b-70effd5a86d5.png)

**Comment by tris90190** [comment]
Sorry but this is working for most other users.
sorry, We will try to fix that in the next update.

**Comment by swordling** [comment]
It's not working for most other users.

**Comment by tris90190** [comment]
We will fix this in the future/next under maintnance

**Comment by swordling** [comment]
What's your username on Dubtrack? @tris90190

**Comment by tris90190** [comment]
@tris90190 you had it yay! LOL!

**Comment by tris90190** [comment]
IM tris i code and am a dev from turn.fm and dubtrack.fm

**Comment by swordling** [comment]
I know you don't represent Dubtrack. It's not my place but please don't pretend that you do.

**Comment by tris90190** [comment]
LOL ok! I still code anyways. 
It has been madness since plug.dj people are shocked it got shut down. I never got to see it shut down. #plugdj4ever

**Comment by tris90190** [comment]
OK i have to go bye! see ya around turn.fm. And Dubtrack. BYE!

**Comment by thedark1337** [comment]
Don't be representing as the developer of the websites when you are not. Telling people it will be fixed when it wasnt from the official devs is very wrong and imo rude. Also turn.off ain't gonna be on anytime soon ;)

**Comment by nambok** [comment]
@emeraldTHC what times are you usually in your room? Ill come by tomorrow and have this sorted for you
