### ISSUE TITLE
music not starting

### ISSUE THREAD

**Issue by wrestlestar** [dubtrack/www-dubtrack-fm#157]
the music in any channel is not starting for me. the queue is full but it comes up for me that no one is playing. i have refreshed many times but still had the same issues.

**Comment by swordling** [comment]
Would you be able to screenshot your Developer Console when you're visiting Dubtrack? https://developer.chrome.com/devtools/docs/console

**Comment by tris90190** [comment]
OK thats a problem with windows firewall nothing with us.

**Comment by swordling** [comment]
It's not an issue with Windows Firewall.

**Comment by nambok** [comment]
we pushed an update for this, closing this for now but feel free to reopen if issues persists
