### ISSUE TITLE
[Feature Request] Allow users to remove their own messages server-side

### ISSUE THREAD

**Issue by netux** [dubtrack/www-dubtrack-fm#158]

**Comment by sinfulBA** [comment]
This is available for users that don't have a rank in the community. Are you suggesting another ' x ' to delete client side messages for staff members?

**Comment by netux** [comment]
Sorry for not being clear. I'm suggesting to let the users without a role in the community be able to delete a chat message they sent server-side (so all users in the room get the message deleted).
I have tried this and it didn't work.

**Comment by netux** [comment]
This has been added, thanks devs!
