### ISSUE TITLE
[Feature request] Add group mentions like @everyone, @mods, @djs

### ISSUE THREAD

**Issue by Not-Kris** [dubtrack/www-dubtrack-fm#160]
Mentions like `@everyone`, `@mods`, `@djs` would really be helpful. 
It should of course be restricted to mods to avoid it being abused, and maybe even the `@everyone` mention to managers and above.

**Comment by tris90190** [comment]
We will fix that later on, thanks for trying though.

**Comment by chrisrohn** [comment]
This was a nice feature in plug.dj and I wouldn't mind having this added, but right now i'd rather have predictive @autofill for user names based on who is in the room.

**Comment by Larry1123** [comment]
This has been added.
