### ISSUE TITLE
[Feature Request] Give mods the possibility to pause someone elses queue

### ISSUE THREAD

**Issue by Fuechschen** [dubtrack/www-dubtrack-fm#164]
As you can read in the title, it would be awesome to give mods these possibility. Sometimes, you don't want to kick someone out of the room, but you are forced to do it in order to get him out of the queue. this feature would resolve this problem.

**Comment by chrisrohn** [comment]
+1 there are many times when I'd like to remove afk's from the queue.

**Comment by PossiblyKris** [comment]
Much needed, if someone has a lot of songs in their queue, you can choose to either spam the room with song removes or kick the user, since locking the queue will lock it from everyone else. All of which would kinda suck.

**Comment by joedubtrack** [comment]
we added a 'remove dj' button. you can find it in the room queue.

**Comment by Fuechschen** [comment]
Awesome :+1:
