### ISSUE TITLE
[Bug] Getting "No one is playing" even if song is playing

### ISSUE THREAD

**Issue by Amibee** [dubtrack/www-dubtrack-fm#166]
I'm having that issue sometimes when I'm in different tab and when song changes and when I'm switching into tab that is dubtrack.fm, it gets "No one is playing", even if song is actually playing. Is anyone having that issue also?

**Comment by joedubtrack** [comment]
By any chance do you know if it was a soundcloud song?

**Comment by RobGoldy** [comment]
I occasionally have this same issue when I leave the browser open for a while. Although it says "No one is playing" there is still audio and when I refresh it shows the song that is playing and continues normally. I'm not sure if it was a soundcloud song but I'll be sure to look out if it happens again.

**Comment by joedubtrack** [comment]
I had this issue for the first time this morning and it was a soundcloud song so I just want to get more feedback from other people experiencing it so we can better track down the issue.

**Comment by Amibee** [comment]
It was a YouTube song.

**Comment by RobGoldy** [comment]
Just had this error happen to me again. It appears that if I temporarily lose internet connection and regain it, it causes this issue. The song will still play and switch to the next one but it will display that "No one is playing" until I refresh.

**Comment by joedubtrack** [comment]
we pushed a fix for this. Let me know if this is still an issue.
