### ISSUE TITLE
[Feature Request] Show 'Guest' users in room

### ISSUE THREAD

**Issue by zewm** [dubtrack/www-dubtrack-fm#170]
It would be nice to show a count of people not logged in but that are in the room. It would let us see if anyone has joined our room but doesn't have a username to show on the current list.

10/15 (10 logged in users, 15 total users) as an example. This can help mods determine actual traffic to their channels. Lots off people check out the room but haven't made an account yet.

**Comment by joedubtrack** [comment]
Currently we just include guests in the total, but that is something we can do as well.

**Comment by zewm** [comment]
Oh, I wasn't aware that guests were even shown. I thought the count was only current users logged in. Thanks for the response.
