### ISSUE TITLE
[Bug] Userlist keeping names of users no longer in the room

### ISSUE THREAD

**Issue by zewm** [dubtrack/www-dubtrack-fm#171]
Whenever a user in my room leaves ,the counter drops to indicate they are no longer there, however their name stays ~~indefinitely~~ for over an hour in the user list.

I'm currently the only person in my room and the counter is showing 1 but the userlist has 2 names.

**Comment by Larry1123** [comment]
I think that this no longer happens. If it still does reopen please.
