### ISSUE TITLE
"No one is playing"

### ISSUE THREAD

**Issue by Puntukas** [dubtrack/www-dubtrack-fm#178]
So im currently in a room alone, and i thought, lemme just play some songs. So i add multiple songs to my queue. Now it only played the first song and then it said "No one is playing" and kept repeating this same song over and over again. I can now see my songs in the "room queue" but the waiting list (the middle bottem) only says either "Loading" or "No one is playing'. Meanwhile other rooms still work. Is this just a bug because im trying to play by myself?

http://prntscr.com/93usok

**Comment by joedubtrack** [comment]
I just reset the queue to your room so it is working again. We will look into it further, thanks

**Comment by thevirtualboy** [comment]
This same thing just happened to me. Except there's three of us here, and it's not playing anything. Is there a workaround for this?

http://prntscr.com/98x23u

**Comment by RobGoldy** [comment]
Try setting the room mode to iframe embed then back to dubtrack mode. Or clearing whoever is 1st in the que's track. Both of those solutions worked previously for me

**Comment by thevirtualboy** [comment]
Thanks, the iframe thing worked.

**Comment by Larry1123** [comment]
I am not sure if this is still happening.

**Comment by KRDemoz** [comment]
Unable to replicate

I frequently listen to my own playlists by myself in my room and I don't think this is happening anymore.

**Comment by ValakhP** [comment]
I'm new to dubtrack, but I think I have similar issue. I'm alone in my room and have a song in queue, but it still doen't play anything, just write: "No one is playing". http://take.ms/qrkEf

**Comment by Al3366** [comment]
Hi,

We are currently experiencing some issues with our system and hope to get them resolved very soon. We will keep you updated. If you have any other issues, please let us know.

**Comment by Al3366** [comment]
Update here: https://github.com/dubtrack/www-dubtrack-fm/issues/314
