### ISSUE TITLE
Soundcloud overdubs itself when in reduced window mode

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#180]
The issue only happens with soundcloud songs when the window is reduced to mini-mode. Soundcloud tracks play multiple copies overtop of itself to produce a very distorted sound.

If the window is in standard chat/video mode, this problem does not occur.

**Comment by RobGoldy** [comment]
I have had this happen several times too. Refreshing the page does fix it
but it does need to be addressed.

**Comment by FranciscoG** [comment]
+1

This happens to me with just about every Soundcloud song that starts playing but I haven't tested the difference between reduced window and full window.  However I'm almost always using the site in a reduced browser tab showing the mobile single column layout

Firefox ver 42
OSX 10.10.5
also happens on FF 42 on OSX 10.9.x

**Comment by Larry1123** [comment]
This needs to be tested again to make sure it is still a bug.

**Comment by KRDemoz** [comment]
Could not replicate, more than likely fixed.
