### ISSUE TITLE
[Bug] Some images 404 after going through proxy

### ISSUE THREAD

**Issue by Not-Kris** [dubtrack/www-dubtrack-fm#183]
Some images get 404 after going through the proxy 
`GET https://dbu1ls7999okz.cloudfront.net/chat?url=https://i.imgur.com/NpnUnh.jpg 404 (Not Found)`
while https://i.imgur.com/NpnUnh.jpg still exists.

**Comment by Not-Kris** [comment]
This is most likely due to the link using the wrong extension (jpg instead of gif).

**Comment by nambok** [comment]
this is now resolved
