### ISSUE TITLE
I don't even know how should I call this problem

### ISSUE THREAD

**Issue by QuickScoperz** [dubtrack/www-dubtrack-fm#188]
So yea, when I enter a room in dubtrack, I can't hear the song nor see the video, and when the song ends I can hear another 1 or 2 songs and see the videos, but after those 2 songs, same happens again. I can't see nor hear so I have to wait untill the song ends. it sucks. I tried using dubtrack on my other pc and it worked fine, so why is it happening on the other pc? pls help

**Comment by joedubtrack** [comment]
That's a bit strange. What browser are you using on the pc that doesnt work and what browser on the one that does? Mac/PC? Old pc? any more detail you can give us can help us hopefully figure it out for you.

**Comment by joedubtrack** [comment]
Also have you tried clearing your browser cache/data?

**Comment by QuickScoperz** [comment]
On both pcs I used Chroome. One of the pcs is old and one of them is new. it works great on the new pc, but the stuff I told about is happening on the old pc. And yea cleared my cache and data. I also tried using another browsers, but same is happening.

**Comment by joedubtrack** [comment]
Is your chrome up to date on the old one? How old is that pc? :p

**Comment by QuickScoperz** [comment]
Yea, it is. And my pc is like 6-7 years old and there is one more thing, my old pc doesn't have graphics drivers installed. Can this be the reason?

**Comment by QuickScoperz** [comment]
I tried installing them but after that my pc does weird stuff like everything disappearing on the desktop :D

**Comment by QuickScoperz** [comment]
Since I'm probably the only one having this problem, this means it's my pc doing weird stuff. but dam, it's not even that shitty, it's still not bad, atleast not that bad that it even couldn't run dubtrack normally

**Comment by joedubtrack** [comment]
haha it's hard to say exactly what the problem is, but sounds like you MAY have a virus if things disappear from your desktop. Do you have anti-virus? Might even be worth backing up your things and simply reformating your pc to start it fresh and clean again. Although, there is no guarantee that dubtrack will work on that pc after doing so.

**Comment by QuickScoperz** [comment]
Hmm...virus...it may be, but I don't think so because previously I had windows vista and I just recently changed it to windows 7, then when I changed to windows 7, I installed graphic drivers, my pc restarted, all good and then when the desktop loads, everything that was on my desktop is gone. when I do system recovery, everything get back to normal.So since then I didn't really download anything on this pc, I use this pc rarely, like listening to music only, so I don't think that there are viruses. I have avira antivirus, I could scan my pc and see if that helps, but i'm like80% sure that are no viruses :D

**Comment by QuickScoperz** [comment]
Well, I don't know, if it's not the browser's fault, then it's definitely my pc. It's strange tho. Never had similar problems with plug dj, it worked fine on the old pc too...so..I don't really know.Thanks for your help, if you still have any ideas, well...you can tell me :D

**Comment by joedubtrack** [comment]
Yeah, sorry I really don't know. I'd reformat :)

**Comment by QuickScoperz** [comment]
Well, maybe i'll do that.Not really a big problem, I can listen to music to myself, I don't really need people hearing what kind of music I listen to xD So yea, Thanks for your help again. Bye :)

**Comment by RobGoldy** [comment]
Can you play YouTube videos or soundcloud songs normally on that PC?

**Comment by QuickScoperz** [comment]
Yep. Sorry for the late reply
