### ISSUE TITLE
Mods cannot add or change other mods

### ISSUE THREAD

**Issue by DrDoctor13** [dubtrack/www-dubtrack-fm#19]
It seems that only the room owner can mod or unmod other mods, mods cannot control it. Is this a bug, or can this functionality be added?

**Comment by japerry** [comment]
It'd be great to have functionality similar to the Room staff on plug. Here is how it was setup:

Mod staff:
Type | Max Users | Add Co-Hosts | Add Managers | Add Bouncers | Add Resident DJs
------------ | -------------  | -------------  | -------------  | -------------  | -------------
Host | 1 | X | X | X | X
Co-Host | 3 |  | X | X | X
Managers | 10 |  |  | X | X
Bouncers | 50 |  |  |  | 
Resident DJs | 100 |  |  |  | 

Room mods
Type | Add to Locked Queue | Skip Tracks | Kick/Ban Users | Rearrange Room Queue | Unban Users
------------ | -------------  | -------------  | -------------  | -------------  | -------------
Host | X | X | X | X | X
Co-Host | X | X | X | X | X
Managers | X | X | X | X |
Bouncers | X | X | X  |  | 
Resident DJs | X |  |  |  |

**Comment by nthitz** [comment]
Edited formatting: (but I always thought they had way too many options, it doesn't need to be this complicated)

Mod staff:

    Type | Max Users | Add Co-Hosts | Add Managers | Add Bouncers | Add Resident DJs
    ----- | ------------- | ------------- | ------------- | ------------- | -------------
    Host | 1 | X | X | X | X
    Co-Host | 3 | | X | X | X
    Managers | 10 | | | X | X
    Bouncers | 50 | | | | 
    Resident DJs | 100 | | | |

Room mods

    Type | Add to Locked Queue | Skip Tracks | Kick/Ban Users | Rearrange Room Queue | Unban Users
    ------------ | ------------- | ------------- | ------------- | ------------- | -------------  
    Host | X | X | X | X | X
    Co-Host | X | X | X | X | X
    Managers | X | X | X | X |
    Bouncers | X | X | X | | 
    Resident DJs | X | | | |

**Comment by nambok** [comment]
this is now being added, there is no limit to how many users you can set. If this becomes problematic we will add the limit :). Feel free to re-open if anything

**Comment by japerry** [comment]
Now we just need some documentation. What is VIP?

**Comment by joedubtrack** [comment]
VIP's can SKIP and join a locked queue
