### ISSUE TITLE
[Bug] Song stuck when rearranging queue at last moment before song advance

### ISSUE THREAD

**Issue by Not-Kris** [dubtrack/www-dubtrack-fm#191]
Sometimes if the room queue is rearranged, or the person in the first spot rearranges their queue, in the last moment before song advance, the song playing will get stuck and will need to be skipped manually.

**Comment by Larry1123** [comment]
I will need someone to test this and see if it is still happening.

**Comment by KRDemoz** [comment]
Tested - No longer happening

**Comment by Larry1123** [comment]
Thanks.
If the bug does show back up reopened.
