### ISSUE TITLE
dubtrack_bot is all weird and overbearing

### ISSUE THREAD

**Issue by rklados** [dubtrack/www-dubtrack-fm#195]
If our bot, or anybody, says a few things in a row, suddenly all of their chat messages in the entire chat log history is deleted?  That's weird.  I don't think this is functioning like it should be, if that's what people were going for?  And I don't see any commits relating to this feature in the repo.

If we're going to try and throttle chat to avoid spamming or something...this probably isn't the way to do it.  If anything, I'd suggest it uses the information available, like low-dubs (which would avoid spam bots entering a new room, since they'd have 0 dubs for that room) or at least not for admins in a room.

**Comment by joedubtrack** [comment]
Is it still blocking your bot? We made some changes a little bit ago

**Comment by rklados** [comment]
Hmm, things seem better but she still got banned once within the last hour and it was for more than 10 min.  Things are working at this very moment, though - thanks for the reply!  I'll let you know if we're able to track down any specific oddness.  Thanks, again!

**Comment by nambok** [comment]
closing this now since it seems to be resolved

**Comment by chrisrohn** [comment]
we are still getting warnings and random mutes on our bot.  our bot is ranked as a co-owner - can managers and owners get immunity from the dubtrack_bot?

**Comment by coryshaw1** [comment]
That still doesn't stop spammers from making their own room and slowing down the servers

**Comment by BenWildeman** [comment]
if your bot is making loads of requests, it's going to get shut down. either stop spamming the bot with commands, or limit the number of messages it can send in a given time frame. my bot gets hammered with commands and never gets destroyed by dubtrack_bot

**Comment by chrisrohn** [comment]
if server load is the concern why are you going back through and deleting chat history? that doubles the load, doesn't it?

**Comment by BenWildeman** [comment]
it's detecting spam, and assumes your bot is a troll. have a limit on how many chats your bot can send within a time frame and you won't have an issue with dubtrack_bot

**Comment by chrisrohn** [comment]
The underlying question then is what is dubtrack_bot for? spammers or server load? If its intended for spammers, owners and managers should be immune.  If it's for server load, the deletion of chat history is only doubling the problem.

**Comment by BenWildeman** [comment]
dubtrack_bot is to limit spamming and trolls. no one is immune from dubtrack_bot. if anyone spams, the bot will warn you, if you continue, it will stop you from being able to message, then finally a ban(?). I'd assume the bot is intended to help rooms with spammers, BUT that said, it also helps with server load. if I was to create a room and then have a bot spam the chat 1000 messages per second, it's going to affect servers. just put a limiter on your bot, half a second will do, and have a good day. your bot won't get destroyed for spamming and it still posts your messages in the chat

**Comment by RobGoldy** [comment]
I'm with Nitro on this one. If the bot is constantly getting flagged by
dubtrack_bot then you should really limit how often the bot responds.
