### ISSUE TITLE
[Bug] Sending two images will make the second one not render correctly

### ISSUE THREAD

**Issue by netux** [dubtrack/www-dubtrack-fm#196]
![Chat messages](https://i.gyazo.com/4d7651c503cb3e55589fb964f3cb2d41.png)
Both are the same images btw, and thats not me.

I have discovered that this is because of a little error while getting the URL from the message.
![Message on Inspect Element](https://i.gyazo.com/6f65f70a9921834aa5acb32286d1eb4b.png)

**Comment by Larry1123** [comment]
Is fixed

**Comment by Larry1123** [comment]
This is fixed
