### ISSUE TITLE
Remove DJ should pause the user's queue instead of clear it

### ISSUE THREAD

**Issue by scytheria1001** [dubtrack/www-dubtrack-fm#200]
When a DJ is removed their queue gets completely emptied.

Our room is testing a method for removing AFK users from the queue but then intention isn't to make them rebuild their queue every time. It would be preferable of removing the DJ would pause their queue, or if that functionality were available as another command.

**Comment by coryshaw1** [comment]
Refer to #184

**Comment by scytheria1001** [comment]
Commented on original issue. thanks
