### ISSUE TITLE
Creators can't give their ownership to another

### ISSUE THREAD

**Issue by RubyDaNinetales** [dubtrack/www-dubtrack-fm#206]
A friend of mine wants to give me a Creator rank because she is too focused on her other room that has a lot of people at a time on it. And I'm on there most. We've already emailed Dubtrack once to change ,but it's been at least 2 months and my rank hasn't changed.

**Comment by nambok** [comment]
the room creator can make you a co-owner of the room, has same rights as the room owner. We will add an option to change room ownership soon, but in the meantime I recommend you to use roles
