### ISSUE TITLE
[Request] Infinite loading of playlist items

### ISSUE THREAD

**Issue by netux** [dubtrack/www-dubtrack-fm#210]
I have  My Queue filled with over 1000 songs, and every time I try to open it my browser freezes.
So I'm requesting that instead of making the playlist load all of the sudden, make it load while you're scrolling (getting to the bottom of the list will make it load more items)

**Comment by RobGoldy** [comment]
As someone with playlists over 3000, I can tell you that the browser does not crash. You just need to click the wait button when it says it is no longer responding. It usually takes like 5-10 mins to load.

However, this loading process does need to be optimized. I agree it should only load the first few and load others as you scroll.

**Comment by chrisrohn** [comment]
This is why previously operating sites limited the number of songs in a playlist.  Not that I want it limited -- I also have a playlist with 3500 songs.  But I also don't see a way to have such lengthy playlists with the ability to shuffle the entire playlist with one click without loading the entire playlist first.

**Comment by nambok** [comment]
@Netox005 we reworked the playlists and now should be much easier to do this, we will be re-touching my queue soon. I also found out so far the biggest playlists has 9k items! hope this update makes song management easier :)

**Comment by crandrade** [comment]
the tab still freezes randomly when listening to a channel :(
