### ISSUE TITLE
[Bug] Annoying issue

### ISSUE THREAD

**Issue by Amibee** [dubtrack/www-dubtrack-fm#216]
I have this issue in dubtrack.fm: Songs doesn't change immadiately, they're stucking, but when I'm refreshing page, it changes song, so I keep refreshing page always when song changes. Also, song suddenly changes to song that is not actually playing, so I have to refresh page to keep playing an actual song.

**Comment by ronaldb** [comment]
Seconded. I've seen it that the same DJ is playing one song, then suddenly it switches to another song. In one case the original song was longer than the second song, and the first song started playing after the first one was finished.
In other cases the first DJ's song is cut short (less than 10 seconds), replaced by the second DJ's song.

**Comment by nambok** [comment]
@Amibee we reworked the queue completely, is this still happening for you?

**Comment by nambok** [comment]
closing this for now feel free to re-open :)
