### ISSUE TITLE
[Bug] New vote system rendering breaks on small resolutions.

### ISSUE THREAD

**Issue by netux** [dubtrack/www-dubtrack-fm#218]
On 1920x1080 (how it's supposed to be?)
![On 1920x1080](http://i.imgur.com/ub8ImAJ.png)

On 1440x720
![On 1440x720](http://i.imgur.com/CdLTHev.png)

and as the the resolution goes lower and lower its width does as well.

**Comment by nambok** [comment]
this is now fixed :)
