### ISSUE TITLE
[bug] dubtrack reports no active song in room

### ISSUE THREAD

**Issue by ghost** [dubtrack/www-dubtrack-fm#219]
A [room](https://www.dubtrack.fm/join/the-igloo) I created is broken as of today. Adding to the queue is reflected in the UI, but the API returns 404s:

```
{
  "code": 404,
  "message": "Not Found",
  "data": {
    "err": {
      "origin": "method",
      "details": {
        "code": 404,
        "message": "no songs in active queue"
      }
    }
  }
}
```

**Comment by ProbablyJody** [comment]
+1
I can add songs to my queue, but they aren't being added to the room queue.

Edit: As I was typing this comment as song started playing. @saiyr you might try it again.

**Comment by ghost** [comment]
Had an admin fix it for me yesterday, so I'll close.
