### ISSUE TITLE
Show who grabs/votes and who enters and leaves.

### ISSUE THREAD

**Issue by Skavau** [dubtrack/www-dubtrack-fm#221]
These may be planned already but I just want outline how I think they should be implemented:

Allow users to set an option in their settings to notify them when someone comes in or leaves. It should just say @User has left the room or @User has joined the room in chat.

For grabs, this could be done in two ways. You could have an option in the settings that says "Show who grabs songs" and have a chat message like "@User has grabbed (song)". If you're feeling adventurous you could make it say "@User has added (song) to (playlist)".

You could also, in the userlist, show a little heart next to the users name. 

For votes you could just show an upvote or a downvote next to the names of users who downvote.

**Comment by Larry1123** [comment]
Everything here is in dubtrack now! Happy Dubbing :)
