### ISSUE TITLE
[Feature Request] Link to Soundcloud option

### ISSUE THREAD

**Issue by Devostar** [dubtrack/www-dubtrack-fm#229]
Whenever a track is played trough Soundcloud, I'd like a way to get a quick link to the Soundcloud page.
For science.

**Comment by Skavau** [comment]
+1

**Comment by netux** [comment]
:+1:

**Comment by coryshaw1** [comment]
I'm thinking like a Soundcloud icon that shows on hover of the bottom left of the artwork. Similar to where and how the YouTube logo appears as a link for YouTube videos.

**Comment by Larry1123** [comment]
This has been added.
