### ISSUE TITLE
Better handling of Queue for Active Djs

### ISSUE THREAD

**Issue by mrgabrielsan** [dubtrack/www-dubtrack-fm#23]
Problem:
It would be nice to have the personal queue more accesible. It's kinda buried inside the UI which is fine for passive listeners, but for people trying to keep a vibe by picking songs that follow the previous one is a bit challenging. 

Possible solution:
a: Moving the queue to the side of the chat with the ability to reorder songs
b: adding a queue tab. This might be the easiest way to implement with the responsive design.
c: having a passive listener layout and an active dj layout (Never seen this before). The truth is that just some users play music, others just listen.

Thanks.

**Comment by rstuckless** [comment]
+1

**Comment by nambok** [comment]
there is a redesign coming soon, stay posted for more details

**Comment by nambok** [comment]
all this was fixed with the new UI, please feel free to re-open if you feel otherwise
