### ISSUE TITLE
Playlist shuffle no longer works on large playlists

### ISSUE THREAD

**Issue by darksabrelord** [dubtrack/www-dubtrack-fm#236]
Since the change to only partially load large playlists was implemented, playlist shuffling no longer shuffles the entire playlist - only the small number of tracks that have already been loaded.

**Comment by Skavau** [comment]
This is deliberate. The entire playlist has to load in order for it all to shuffle at once.

This is done so that users who just want to select a song or two in a 500+ song playlist don't have major slowdown or browser crash. I would be in favour of a little button that says "Load All" for people who want to mass shuffle their playlist.

otherwise you can shuffle your queue.

**Comment by darksabrelord** [comment]
The playlist shuffle button is largely meaningless then - there's not much point (or necessity) for a user to shuffle 30 tracks.

For example, I have several playlists with 400+ tracks in them. With the new setup, I am pretty much guaranteed to never see the tracks making up the bottom half of any of them. Scrolling to the bottom can take a minute or even more time for the largest of the lists because the only way to get more files to load is to continually scroll down with the mouse (the home/end keys don't work in the playlist window, but even if they did it would take a long time to load the list piece by piece.

Previously if users shuffled the lists before adding songs to their queue they had easy access to these tracks since they'd be brought to the top. Without this or a 'load all' button as you've described, it's all but impossible to access the later songs in a very large playlist and any slight misclick causes the playlist window to close. There's no playlist export option, either, so it's impossible for users to break up a very large playlist into several smaller ones.

EDIT: this is all complicated further by the fact that new songs are appended to the end of the playlist when added

**Comment by RobGoldy** [comment]
Are you sure that it is working as you described? I just tested it with a
680 song que and it shuffled the bottom songs...

Just tested it with a que with over 1,200 songs and it also shuffles
the entire que. I kept track of songs at the bottom and they were 100%
moved.

**Comment by RobGoldy** [comment]
Ah, i see the difference. If you add the entire playlist to the que first and then shuffle the que, then the shuffle button will work as I am describing above and your browser will load fast. If you want to shuffle the playlist BEFORE adding them to the que, then you will encounter the problem you are having. 

Best solution is to add the entire playlist to the que and then shuffle it from there.

**Comment by Skavau** [comment]
> The playlist shuffle button is largely meaningless then - there's not much point (or necessity) for a user to shuffle 30 tracks.

Sure, but I'm telling you why it was gotten rid of. Surely is more meaningful to shuffle your queue not your playlist.

> Previously if users shuffled the lists before adding songs to their queue they had easy access to these tracks since they'd be brought to the top. Without this or a 'load all' button as you've described, it's all but impossible to access the later songs in a very large playlist and any slight misclick causes the playlist window to close. There's no playlist export option, either, so it's impossible for users to break up a very large playlist into several smaller ones.

Actually, to the contrary, if the window closes it remembers what you've scrolled to.

> EDIT: this is all complicated further by the fact that new songs are appended to the end of the playlist when added

That doesn't happen for me.

**Comment by ghost** [comment]
Even if you decide to retain only this behavior, I would suggest adding some indication that playlist shuffle only works on the first few songs.

**Comment by darksabrelord** [comment]
> Sure, but I'm telling you why it was gotten rid of. Surely is more meaningful to shuffle your queue not your playlist.
> 
> Best solution is to add the entire playlist to the que and then shuffle it from there.

That is true, but without the ability to shuffle the playlist there's no easy access to the songs at the bottom. One option is pulling the whole list into your queue then shuffling, but this doesn't work well if you want a few songs from several different (large) lists each in your queue.

> Actually, to the contrary, if the window closes it remembers what you've scrolled to.

It hasn't been working this way for me - just tried it again and I had to start at the top of the playlist I had open. I don't have Adblock or anything running. When the playlist window is reopened it starts at 'My Queue'.

A 'Load All' button would solve all these problems.

**Comment by swordling** [comment]
@darksabrelord Is correct. But instead of a load all button shuffling playlists should automatically load all playlist items and then shuffle them for better UX. But I also think shuffling playlists should have _heavy_ rate-limiting in place (Only allowing people to shuffle once on the front-end, requiring them to refresh to shuffle playlists again and adding a limit of 3-5 shuffles per day per user). Plug.dj used to IP ban users for 15 minutes for repeatedly shuffling playlists because it carried a big payload and I imagine when you playlists are large can consume quite a bit of usage too.

**Comment by darksabrelord** [comment]
I don't think a 'Load All' should do _any_ shuffling at all, but I think it is necessary regardless of any tweaks to the shuffle function because as Dubtrack stands right now there's no easy way to add a few songs from the bottom of a large playlist to your queue.

**Comment by Skavau** [comment]
> That is true, but without the ability to shuffle the playlist there's no easy access to the songs at the bottom. One option is pulling the whole list into your queue then shuffling, but this doesn't work well if you want a few songs from several different (large) lists each in your queue.

You can still search for specific songs with "Filter Playlist".

In any case a good compromise would be to have a button that says "Load All".

**Comment by swordling** [comment]
Excuse my Grammar. I meant to say that clicking the shuffle button should load all playlist items, not the other way around. I don't think we need a Load All button though, like @Skavau said there is the filter option and if you do want to access the bottom item just scroll to it. Pagination is there for a reason and it shouldn't be easily avoided.

**Comment by Skavau** [comment]
> I don't think we need a Load All button though, like @Skavau said there is the filter option and if you do want to access the bottom item just scroll to it.

Well when you've got 300+ songs that could take a while. A "Load All" button is a good go-between for people who really want to mix up their playlists. I wouldn't regard it as a priority feature at all though. Much more important things to add.

**Comment by japerry** [comment]
Queuing the 'on deck' playlist is already a UX headache for folks. Managing two playlists, what? (Especially if you come from Plug or TT) ---  We've been noticing the same tracks playing every day or so, which is really annoying for rooms that are used to going through 500+ songs before a repeat.

This is a serious problem for smaller rooms, and probably partially why audience numbers are going down since December.

**Comment by JTBrinkmann** [comment]
it's _definitely_ no permanent solution (at all), but as a quick work around, people can split their playlists into smaller chunks using https://github.com/JTBrinkmann/Dubtrack-Playlist-Pusher

I've updated it today to add a Split Playlist button, with configurable chunk sizes.
This way, people don't have to scroll down for ages, to reach the bottom of their playlists, anymore.
