### ISSUE TITLE
Room Option: Allow room owners to block all non-Resident DJS from posting pictures.

### ISSUE THREAD

**Issue by Skavau** [dubtrack/www-dubtrack-fm#239]
The room queue on Dubtrack is viewable for all. This makes room trolling through DJing pretty hard, if not almost impossible.

That said, anyone can spam pictures and I've seen them do so. Allowing room owners to block all images coming through from all non-resident DJs seems like a good fix. Would also help prevent general picture spam as well.

**Comment by netux** [comment]
I mean, you can always tell people to disable images or use a bot and remove the messages containing images. But yeah :+1:

**Comment by Larry1123** [comment]
Since this was made there was a requirement added to inline images in chat. Users are required to have at lest 100 dubs in the room.

If people still feel this is something that maybe wanted comment about that. If it is still wanted it can be reopened.
