### ISSUE TITLE
Replay on song preview plays song twice if song is from Soundcloud

### ISSUE THREAD

**Issue by netux** [dubtrack/www-dubtrack-fm#244]
When you preview a song from Soundcloud and it finishes, clicking the replay button plays the song twice (the second one usually takes a few seconds).
When you close preview the first play stops, but the second keeps going. Only way to stop it is by refreshing or waiting for the song to end.

**Comment by Larry1123** [comment]
Is this still valid?

**Comment by netux** [comment]
Yes, only way to fix is refreshing.

EDIT: Edited issue description to provide a better explanation.

**Comment by Larry1123** [comment]
Thanks!

**Comment by netux** [comment]
This has been fixed for some time now ;)
