### ISSUE TITLE
[Request] Can you make it so all site or even just https sites Allow-Origin not just dubtrack.fm

### ISSUE THREAD

**Issue by Mitchdev** [dubtrack/www-dubtrack-fm#246]
What I am trying to do it post current song and person playing song on my site but I am unable to do this as dubtracks api only allows dubtrack.fm to do this.

https://mitchdev.net/i/2016-01-18_22-13-00.png

It would be nice if this could be changed.

**Comment by RobGoldy** [comment]
I tried pushing for this change but nambok rejected it because it's easy to click jack people (even though that's neither of our intentions)

btw check out my website, I do what ur tryna do ;p http://upcomingrecords.com

**Comment by PossiblyKris** [comment]
[Off-topic] @RobGoldy Your scaling seems to be off 
![image](https://cloud.githubusercontent.com/assets/12618255/12420362/7bf15d78-bebc-11e5-90c7-f74d35b601a9.png)
Below 1680px width it seems to at least show the full page, but anything over that will ruin it like above.
![image](https://cloud.githubusercontent.com/assets/12618255/12420432/d65802c6-bebc-11e5-8cda-d828ae409a20.png)

**Comment by chrisrohn** [comment]
We do this at http://www.indiediscotheque.com/ by using the lastfm api and scrobbling.
