### ISSUE TITLE
[Issue] Some songs doesn't change immadiately

### ISSUE THREAD

**Issue by Amibee** [dubtrack/www-dubtrack-fm#249]
When songs ends, they just stuck and they don't change immadiately, but they changes some seconds later, but you need to refresh page if song is stucking for a long time.

**Comment by gamedevsam** [comment]
Same, never changes for me.

**Comment by joedubtrack** [comment]
It never changes for you? What room are you in? What is your username? Please give us more details when you submit a bug :)

**Comment by gamedevsam** [comment]
I'm in room [trance-progressive-whre](https://www.dubtrack.fm/join/trance-progressive-whre), my username is **crazysam**, sorry for the lack of info, since I don't see any errors on the console it's hard to know where to start looking.

**Comment by RobGoldy** [comment]
Shoutout to swordling for originally making this, but please post the following information so the issue can be addressed the issue ASAP
1. Your OS, OS Version, Browser and Browser Version.
2. Results on different browsers, unless you’re certain this isn’t browser related.
3. _Detailed_ description of the issue - What is actually broken? 
4. Screenshots, screenshots and more screenshots. Screenshots of the bug, screenshots of the console and screenshots of the network tab. Even if the console and network tab aren’t showing anything, prove that to the developers.
5. _Very very very very very detailed_ steps to replicate the issue.

**Comment by gamedevsam** [comment]
1. Windows 7 x64
2. Issue reproduced both in Chrome (48.0.2564.97 m) and Firefox
3. Song never switches when it stops playing (that's it, really).
4. Screenshots:
   ![dubtrack_console](https://cloud.githubusercontent.com/assets/420996/12796813/c3e8534c-ca8e-11e5-8a40-41996b533e3b.png)
   ![dubtrack_network](https://cloud.githubusercontent.com/assets/420996/12796814/c3e8ed48-ca8e-11e5-8937-2b9f8e64493c.png)
   ![dubtrack_network_2](https://cloud.githubusercontent.com/assets/420996/12796867/0a09a948-ca8f-11e5-8435-ced8e5d0febb.png)
5. Log in, join room, wait till song ends, wait forever in sadness.

Please let me know if this helps, or if I can provide more info.

Here's another screenshot of my network tab, but this time I refreshed the game right before the song was over:
![dubtrack_network_3](https://cloud.githubusercontent.com/assets/420996/12797142/776a7c3c-ca90-11e5-8e62-083db56388b3.png)

Also, maybe this helps, maybe not, but I put a breakpoint in `function videoEnd()`, and that did trigger successfully as soon as the song was over, but I couldn't track down where the code failed to trigger a new song to play.

**Comment by Larry1123** [comment]
This should no longer be an issue. However this may happen from time to time. We have been working on making sure this never happens.

**Comment by Larry1123** [comment]
What was causing this should not longer be happening at this time.
If it comes back it is likely to do with another issue to make a new issue.
Thanks.
