### ISSUE TITLE
Player should offer alternative tracks when a track cannot be played.

### ISSUE THREAD

**Issue by japerry** [dubtrack/www-dubtrack-fm#25]
Because youtube and soundcloud tracks can die, be unavailable in certain countries, etc -- plug.dj had a feature that allowed a user to individually select a track to play in its place. If the times didn't sync, that was okay, the socket server just ended the song when the original song playing was supposed to end. 

It'd be great to have this feature, especially for our european friends who have a different set of allowed YT videos.

**Comment by chrisrohn** [comment]
Even better would be to have the first available alternate automatically play. A lot of us use this as a radio service and can't actively monitor what to skip or select while working. Soundtrack.io has a feature like this and it works!

**Comment by nambok** [comment]
thanks @chrisrohn closing this since is a repeated ticket
