### ISSUE TITLE
[Feature Request] Autofill Mentioning

### ISSUE THREAD

**Issue by iSpaceCadet** [dubtrack/www-dubtrack-fm#258]
I was wondering if it'd be possible to get Autofill mentioning when mentioning another user in a room. For example my name on Dubtrack is SpaceCadet, I'd like to have it so when I start typing "@Spa" the name will appear and i won't have to finish typing it out. Thoughts?

**Comment by Fuechschen** [comment]
DubX has this feature, if you want it

**Comment by RobGoldy** [comment]
it already exists on dubx but still this would be a good feature to implement in the general website

**Comment by Larry1123** [comment]
This would be a nice thing to add yes. If I have the time I will see about this.

**Comment by Larry1123** [comment]
This is a duplicate. #10
