### ISSUE TITLE
Skip tracks

### ISSUE THREAD

**Issue by aemxdp** [dubtrack/www-dubtrack-fm#26]
There should be some way to skip tracks. Any troll may enter a room and play a 15hours video with some memes. It seems skipping such things is not possible currently.

**Comment by japerry** [comment]
In addition to that, it'd be good if admins could remove tracks from the queue.

**Comment by zewm** [comment]
I'm a mod in my room and I have a skip track button on the top right of the video.

However it seems to sometimes disappear on me and I have to refresh the page.

**Comment by coryshaw1** [comment]
Is there any percentage of Dubdowns to users that would force a skip?

**Comment by aemxdp** [comment]
Also we've found there is a chat command /skip for moders, but sometimes it doesn't work. And by the way, if you are sitting in two rooms simultaneously, skipping in one room may result in attempts to skip in another (and there will be chat messages "Moderator skipped track" there even if you're not moderator, but actual video will not get skipped in that case).

**Comment by Leykis** [comment]
Users currently do not have the option to skip their own song, but should. If the song is dead and no mod is available in the room to skip, we sit in silence for the duration of the song...

**Comment by nambok** [comment]
this is now done, mods can remove users as well as current dj can skip the song :)

**Comment by scotmcgovern** [comment]
Would still be nice if half the room or more downvote, it auto skips.

**Comment by Leykis** [comment]
The skip option has seem to disappear and is no longer available to either users or mods..
