### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ulamnet** [dubtrack/www-dubtrack-fm#261]
Hello , how to install this script?

**Comment by Fuechschen** [comment]
All install instructions can be found in [readme.md](https://github.com/dubtrack/www-dubtrack-fm/blob/staging/README.md).

You may missunderstood this repo. This isn't an extension for dubtrack, it is the front-end (what you see, when you open https://www.dubtrack.fm) itself.

**Comment by Larry1123** [comment]
It sounds like you were looking for some form of extension.
