### ISSUE TITLE
Error loading text symbols in Dubtrack rooms with Windows 7

### ISSUE THREAD

**Issue by darksabrelord** [dubtrack/www-dubtrack-fm#271]
Tried joining rooms with a Windows machine and multiple browsers, I see the following in Chrome  49.0.2623.110 m : ![Chrome window](http://i.imgur.com/vhPRA75.jpg)

A similar issue presents in Internet Explorer and Firefox, but only in Windows. This issue can be replicated on different machines and is unaffected by clearing the browser cache.

**Comment by Mitchdev** [comment]
There was a dns issue it should be coming right soon. :smile:

**Comment by netux** [comment]
DNS Issue, nothing to do with your operating system.
Dubtrack devs are working on it :)

EDIT: Mitch was faster than me >_<

**Comment by darksabrelord** [comment]
Issue resolved, thank you!
