### ISSUE TITLE
[Bug] Can't import soundcloud playlists

### ISSUE THREAD

**Issue by alanqchen** [dubtrack/www-dubtrack-fm#275]
I entered my soundcloud username, and it does nothing.
I also did "nodinawe/sets/dubtrack", and that also did nothing.
Am I doing something wrong?

**Comment by starnixce** [comment]
Soundcloud recently did some updates so we will need to update our importer as well.

**Comment by lukechatton** [comment]
This is still an issue. Would love to be able to import my soundcloud lists!

**Comment by Al3366** [comment]
Hi,

Sorry for the late response. Due to some updates SoundCloud did on their end, it unfortunately broke our importer and we've yet to find the root of the issue. We will keep you updated on our progress.

**Comment by Al3366** [comment]
Hi,

An update on our progress - We have found the root cause of the issue and are rolling out a patch for it within the next 24 hours. 

Sorry for the inconvenience.
