### ISSUE TITLE
List view for users

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#28]
It would be easier to view who is in the room with a user name list view option without avatars.

**Comment by chrisrohn** [comment]
this would especially be nice in mini-mode, where as of this morning avatars don't display any more and all i see is a matrix of point counts without the ability to click on them.
![untitled2](https://cloud.githubusercontent.com/assets/11859955/10168453/da03ac4c-669a-11e5-8ab3-97f2338c81a9.png)

**Comment by nambok** [comment]
this is now done feel free to reopen if anything
