### ISSUE TITLE
Suggestions for Preview Video

### ISSUE THREAD

**Issue by KRDemoz** [dubtrack/www-dubtrack-fm#286]
1) Remember previous volume. Possibly match it to the room video volume? Really annoying that every time you preview a song it defaults to max volume.
2) Sound cloud links. It would be helpful for us in our room to be able to check who produced sound cloud songs before they actually play.
3) Show song name and User who queued it on the preview screen itself. (https://github.com/dubtrack/www-dubtrack-fm/issues/139)
4) Display soundcloud cover on preview instead of dubtrack logo. (https://github.com/dubtrack/www-dubtrack-fm/issues/245)

▼▼BUGS BELOW▼▼

1) room video unmuting during preview if room video advances to the next song (https://github.com/dubtrack/www-dubtrack-fm/issues/227)
2) Soundcloud songs continue playing even after closing preview if you used to "replay" button on preview. (https://github.com/dubtrack/www-dubtrack-fm/issues/244)

Compiling these here for ease of access.

**Comment by mtomcal** [comment]
I looked into "Remember previous volume. Possibly match it to the room video volume? Really annoying that every time you preview a song it defaults to max volume." and have some patches. Should be able to get PR up in the next couple days or so. Is there an individual issue number for this? Thanks, this is my first time contributing. My username on dubtrack.fm is "TomRone".

**Comment by Larry1123** [comment]
All of the things here are now on live.
