### ISSUE TITLE
How does one get grey text?

### ISSUE THREAD

**Issue by ornithologistnightmare** [dubtrack/www-dubtrack-fm#290]
![image](https://cloud.githubusercontent.com/assets/7671948/16405148/6d232604-3cfd-11e6-89c2-c6d4299c42da.png)

I've seen people who are able to do this when they have access to the commands. I can get it using "/message" but it types "/message" in the message itself.

I think it's something to do with chat-me-command-joined, though I don't see any references to "/message".

**Comment by qaisjp** [comment]
`/me lelelele`

**Comment by ornithologistnightmare** [comment]
@qaisjp Thanks!

**Comment by qaisjp** [comment]
@DeathHammer000 Please click the "close issue" button
