### ISSUE TITLE
[Feature Request] Ability to see soundcloud links when previewing the song.

### ISSUE THREAD

**Issue by Iztooi** [dubtrack/www-dubtrack-fm#296]
Hello,
Since dubtrack has its own sorting when searching on soundcloud music and sometimes it takes so much to replicate researches on both dubtrack and soundcloud, I was wondering if it could be possible to add a soundclound link in the preview mode. When listening to a song there's the usual right-lower corner youtube/soundcloud icon that redirects you to the song link. Youtube previews have the icons but soundcloud doesn't. The only way i found to have a precise song link (other than searching it on soundcloud site) was to create a private room, add the song and clicking on the icon, but there's a "cooldown" when you want to re-add that same song in the queue.
Sorry for the wall of text, and thank you for reading.

**Comment by Larry1123** [comment]
This is done!
