### ISSUE TITLE
Online count is not the same for all users

### ISSUE THREAD

**Issue by netux** [dubtrack/www-dubtrack-fm#306]
![It's waaaaaaay off](http://i.imgur.com/leuqJ4Z.png)

Notice how bubbles said 58+58 but they were 68 in queue, which doesn't make sense.
Refreshing the page doesn't fix it.

**Comment by Larry1123** [comment]
I have been looking over just what may be causing this have not yet been able to pin it down.

**Comment by Larry1123** [comment]
This should be stable now. I will keep track of this.

**Comment by Larry1123** [comment]
This should be fixed now.

**Comment by netux** [comment]
Some users still report this bug, can you reopen?

Someone said he saw 276+317 when everyone else was seeing 112+135, made him refresh and then he reported 112+135.
He said he left Dubtrack open for some time, could it be Dubtrack not working properly when the tab is not focused?

**Comment by Larry1123** [comment]
It is not the same issue.
