### ISSUE TITLE
Auto-linking breaks some URLs

### ISSUE THREAD

**Issue by ghost** [dubtrack/www-dubtrack-fm#311]
Not sure if is specifically due to the insertion of the open-in-a-new-window icon but if the URL has a parenthesis at the end ( e.g. https://en.wikipedia.org/wiki/Artificial_intelligence_(video_games) ), the icon is inserted before it and breaks the link.

**Comment by netux** [comment]
The problem is the way the URL is being detected, the icon is inserted as an after pseudoelement (so it shouldn't break the text in any way)
Thanks for reporting

**Comment by netux** [comment]
Ok, after 19 days I finally got the time to fix it. Will be fixed on next update.
Will leave issue open until the fix is pushed to production

**Comment by netux** [comment]
Well, this is embarassing. Totally forgot about this issue!
It's been fixed for a few months now, closing.
