### ISSUE TITLE
autocomplete doesn't consider "@djs" or "@everyone" valid tags

### ISSUE THREAD

**Issue by darksabrelord** [dubtrack/www-dubtrack-fm#312]
Not sure what else it's missing but tags that aren't usernames don't autocomplete. They still work if entered manually without tab-autocomplete.

@djs and @everyone currently auto-complete to whoever in the room has the most alphabetically similar name

**Comment by netux** [comment]
Fixed in beta ;)
Will keep issue open until we push everything to production

**Comment by netux** [comment]
Fixed!
