### ISSUE TITLE
Can't Skip

### ISSUE THREAD

**Issue by Gaster666** [dubtrack/www-dubtrack-fm#314]
Me and my friends are having problems skipping songs in our room, and of course, someone put on a 10 hour song that we can't skip now.

This is the room we are having the problems in: https://www.dubtrack.fm/join/frens

**Comment by Al3366** [comment]
Hi,

Sorry about the issues you've been having recently. Our system hasn't been feeling very well lately, but as of right now Dubtrack looks to be stable and running fine. We will continue to monitor the service for the time being. If any more issues do arise, please do let us know here.

**Comment by Al3366** [comment]
UPDATE:

We have spammed a few buttons and now things are looking good. As it stands, users can now join queues, skip songs and songs are advancing as they should. Sorry for any inconvenience caused by this.
