### ISSUE TITLE
Soundcloud?

### ISSUE THREAD

**Issue by KiritoSoFuego** [dubtrack/www-dubtrack-fm#321]
The soundcloud link isn't working, which means I cant login to my main account, which I need to run my room. Please fix this soon. Thanks for reading.

```
         Kindest
                       Regards,
                                                  KiritoX
```

**Comment by Al3366** [comment]
Hello,

I will get someone to look into this now. Sorry for the inconvenience.

**Comment by KiritoSoFuego** [comment]
Thanks, really appreciate it.

**Comment by Al3366** [comment]
Hi,

We are working on fixing the issue now. In the meantime, if you give me your username and a preferred email, I can switch your account over so you can login with that instead.

**Comment by KiritoSoFuego** [comment]
KiritoX (username)
elijahdanelevingston@gmail.com (email)

**Comment by Al3366** [comment]
Hi,

I will get this done for you ASAP and update you when it's ready.

**Comment by KiritoSoFuego** [comment]
Okay. thanks.

**Comment by Al3366** [comment]
Hi,

I haven't added an email to your account as we've patched the issue. Sorry for any inconvenience.

**Comment by KiritoSoFuego** [comment]
Okay.
Its fine
