### ISSUE TITLE
[Feature Request] Import YouTube Playlists

### ISSUE THREAD

**Issue by cassidoo** [dubtrack/www-dubtrack-fm#33]

**Comment by chrisrohn** [comment]
duplicate of #3

**Comment by joedubtrack** [comment]
@cassidoo Hey Cassidy, thank you so much for contributing! If you like, we have a SLACK for our developers as well as other volunteers working on the project. We would love to have you around :)

**Comment by cassidoo** [comment]
@joedubtrack I'd love to!  How can I join?

**Comment by joedubtrack** [comment]
@cassidoo send me an email joe@dubtrack.fm and ill send you an invite
