### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by wambaloo** [dubtrack/www-dubtrack-fm#331]
Hi !!

I follow installation instructions but I can't login dubtrack locally. I create an account online for testing, I login online, but when I display my local site, I'm not login. 
I can see that all requests sent to dubtrack api send me a 301 response (like http://staging-api.dubtrack.fm/auth/session for example). I think it's because of this.
I tried a CORS extension on google chrome but I have errors too for same requests. 
What did I missed ?

Thanks in advance.

**Comment by Al3366** [comment]
Hi,

We're no longer supporting this version of Dubtrack and thus, our Staging API is offline. Sorry for the confusion.
