### ISSUE TITLE
dubtrack asks to reload when i tab back to it.

### ISSUE THREAD

**Issue by chalda** [dubtrack/www-dubtrack-fm#334]
i can see someone is playing, i can see the chat but i get a modal+backdrop that asks me to refresh. after doing so all the chat history is gone.
On macOS Mavericks +  Chrome (Canary)

**Comment by Al3366** [comment]
Hi,

I'm sorry to hear you're having issues with the site.

Please could you email me at support@dubtrack.fm with as much detail as possible so we can get this looked in to?
