### ISSUE TITLE
Remember Chat Notification Sound Option

### ISSUE THREAD

**Issue by andrewtibbetts** [dubtrack/www-dubtrack-fm#37]
Right now it always reverts back to `ON` on refresh. I would say at the very least make `@MENTION` the default (assuming that's the most used option, but I could be wrong).

**Comment by chrisrohn** [comment]
+1

**Comment by coryshaw1** [comment]
My `@MENTION` sounds don't work to begin with. I did change my name from the default since I signed up using Facebook if that could cause any problems. Somebody `@MENTION`ing my old default name doesn't cause a notification either.

**Comment by joedubtrack** [comment]
We will be changing @mention to default and add a different ping noise than the all chat.

**Comment by Leykis** [comment]
I am having an issue with the @mention sounds not working, not sure if it's an issue with the actual ping noise or the actual function.

**Comment by nambok** [comment]
this is now fixed
