### ISSUE TITLE
A 'clear queue' button

### ISSUE THREAD

**Issue by darksabrelord** [dubtrack/www-dubtrack-fm#39]
A single button by which users can erase their entire active song queue.

**Comment by coryshaw1** [comment]
And to add to this, a "bring to top" button for any track in the playlist

**Comment by darksabrelord** [comment]
I'm particularly interested in a 'clear queue' because it makes it easier for users to walk away/be AFK without worrying about what they queued up (or if they move between rooms with different genres). Bring to Top, Send to Bottom would also be great.

**Comment by chrisrohn** [comment]
this is a part of #8

**Comment by japerry** [comment]
This specific issue has been fixed by nambok.

**Comment by nambok** [comment]
correct :) #8 still open and we will try to add those functions soon
