### ISSUE TITLE
Editing 'My Queue' drops you to the bottom of the room queue

### ISSUE THREAD

**Issue by coryshaw1** [dubtrack/www-dubtrack-fm#40]
Queuing songs at separate times causes the most recent songs to be put at the top of "My Queue" rather than at the bottom. Not sure if changing your next song in "My Queue" is what causes the position loss for the room queue, or if just adding to "My Queue" in general causes it.

**Comment by nambok** [comment]
@coryshaw1 this should now be fixed :)
