### ISSUE TITLE
Changing the room background resets the song playing to the start of the song

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#41]
If the room background is changed, the current song playing resets to the start of the song.  Users require a refresh to get back to where we were previously in the song. This can be especially annoying for everyone in the room when testing out numerous backgrounds / versions of images.

**Comment by japerry** [comment]
Verified this occurs upon upload.

**Comment by nambok** [comment]
this should now be fixed. Please feel free to reopen if anything
