### ISSUE TITLE
having an X on every chat message is annoying and unsightly

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#47]
there must be a better way

**Comment by coryshaw1** [comment]
Just `display:none;` then `display:block;` on hover of the <li> element of the chat, may be able to make a nice transform to display it subtly.

I can work on this later, I'm pretty busy at work today so it won't be for a few hours.

**Comment by coryshaw1** [comment]
I made a pull request with a60923b and  420e722 that fixes this with mobile support. The transition was too much in my opinion, but I'm open to opinions.

**Comment by japerry** [comment]
I think the onhover looks much better!

**Comment by nambok** [comment]
closing this for now, feel free to reopen
