### ISSUE TITLE
Dub vote location

### ISSUE THREAD

**Issue by Hebgbs** [dubtrack/www-dubtrack-fm#48]
Moving it from the bottom-right of the page to the bottom-right of the video player (opposite where the socmed icons are) would not just allow for longer titles to be displayed without cutting it off, but it would also be a visual cue to the end-user that the current video / song is being voted on, and it would require less mouse movement from chat to the video player.

Alternatively, if you were to swap position of the socmed icons and the vote / add to playlist buttons, the vote buttons can take up a wider space which would be more touchscreen-friendly. Also, all the space on the bottom can house the song info and duration in "Mobile mode" since there's nothing really there in this other configuration I am suggesting.

**Comment by chrisrohn** [comment]
not everyone uses the video pane all the time.  I use dubtrack almost exclusively in mini-mode on the chat pane and it is wonderful to have the vote buttons / vote count visible as they are.

**Comment by parkeerwacht** [comment]
Maybe in mini mode the vote buttons could also be displayed on the chat pane then

**Comment by coryshaw1** [comment]
@parkeerwacht They already are:
<img width="386" alt="screen shot 2015-10-03 at 7 48 53 pm" src="https://cloud.githubusercontent.com/assets/5014172/10265660/e1d148d8-6a07-11e5-960a-ab56eaf3e2e3.png">

**Comment by RobGoldy** [comment]
I also use chat only mode (from DubX) sometimes and as a result want to keep the buttons as-is

**Comment by Larry1123** [comment]
The UI has changed if you feel this should be brought back up reopen please.
