### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by xSidewinderx** [dubtrack/www-dubtrack-fm#5]
https://gyazo.com/e51d41887071e9e1b7894171b953bd32

**Comment by nambok** [comment]
Did you run grunt dev?

**Comment by xSidewinderx** [comment]
How do I run it?

**Comment by nambok** [comment]
make sure your install:
 - [nodemon](https://github.com/remy/nodemon)
 - [grunt-cli](https://github.com/gruntjs/grunt-cli)
 - [compass](http://compass-style.org/)

go to your repo folder and run:
```
npm install
grunt dev
```

closing this for now, but feel free to re-open if you have any more questions
