### ISSUE TITLE
Mention Sound

### ISSUE THREAD

**Issue by Ruin332** [dubtrack/www-dubtrack-fm#52]
The mention sound should not be as "scary" as it is. It sounds like someone took the waveform of a dialup sound and smashed it all together to be played in 1 sec. It sounds awful and I think I almost fell out of my chair the first time I heard it. Many others also say that the mention sound is unnecessarily intrusive/annoying. Also, I think the mention sound transcends the power of the sounds off button and the mention sound will still play.

**Comment by nambok** [comment]
this is now updated, please reopen if sound still scary. Also please add a preferred sound if possible :)
