### ISSUE TITLE
multi-select in playlists [feature request]

### ISSUE THREAD

**Issue by Twiguard** [dubtrack/www-dubtrack-fm#53]
It would sooo make managing of songs in playlist easier. I'm used to playlists with hundreds of songs and adding 20 new songs of one band and distributing them across the whole playlist is such a pain now. Because I need to go all the way to the end (or beginning) where they dwell, take one, drag it to the desired position, go back to start, drag a new one, find the old one again, drop it somewhere else. Scrolling the playlist while you drag would also make it more convenient. I got used to using arrows instead though.

**Comment by nambok** [comment]
this was done :)
