### ISSUE TITLE
player issues on low performance computer

### ISSUE THREAD

**Issue by Eckerdecker** [dubtrack/www-dubtrack-fm#54]
Hello,

I don't know how to describe better this issue, because it is not exactly the same one day or another, but it's on my both computers here, at work, one is on windows 7 and the other is on MacOS X 10.7.5, pretty old, with low memory, but for now I never had any problem on any music site, youtube videos are allways loading properly, whatever the browser I could use.

But on dubtrack, my whole memory is used, and the player is acting very weird, today is the worst since I start to go on dubtrack: between two tracks the player is telling me it's loading ("loading ..." in the timeline), it loads and plays the first second of the last track (indicating "BUFFERING..." or "LOADING.." then it disapears and apears in loop in the video player), like tens of times, during minutes! And when finally it skips this really annoying step, it loads the next track at 2:00 or sometimes later of its beginning!

Please, something has to be done here.

**Comment by nambok** [comment]
@Eckerdecker can you try again. I tried on a pretty old computer and seemed fine :)

**Comment by Eckerdecker** [comment]
@nambok long time i didn't sign in Dubtrack, it seems many things have changed, and yes, I no longer have those issues i had. Good job!

**Comment by Eckerdecker** [comment]
Well maybe I spoke too fast, I'm experiencing similar issues as in october, meaning songs starting at their middle, playing until their end and then restarting from beginning until the point they started first.

**Comment by Larry1123** [comment]
@Eckerdecker If you are still having this happen reopen this please.
