### ISSUE TITLE
Music replayed for 1 min and after, load the next one 1 minute ahead

### ISSUE THREAD

**Issue by Goutye** [dubtrack/www-dubtrack-fm#55]
The problem doesn't appear on every configuration but my friends and I have this problem since 10/02 (today).
I will detail the problem:
- The music ends.
- The music is replayed for some seconds and replayed again and again just for a couple of seconds until 1 minute passed. (https://i.gyazo.com/6bec4d852a90efccfb2d0e131ebec93b.gif https://i.gyazo.com/078a14b37ad09dbc4965a80ff8ce5ca1.gif). The song name is displaying "Loading...".
- The next music is played but this one starts at 1 minute on the whole duration. (https://i.gyazo.com/6cf2fa1a136944b59dfa1ac481efe196.png )

This happens every time a music is played since today. Both on Chrome and Firefox. Maybe it is a problem of location or way to know when dubtrack has to load the next song (such as clock) because I am living in France (My friends too). The issue is not related to US members so...

EDIT:
"There was an error calling back an event handler for "firstFrame". Error: b is null YdjEPKIi.js:1:14313" x 11-19
during the "replaying" of the music.

EDIT2: Real time: 1min05 ; Every 5 sec, buffering & replaying of the previous music.

**Comment by stevenlr** [comment]
Same here, but it lasts 30 seconds for me, not 1 minutes.

**Comment by Goutye** [comment]
Since the last update, the music is not replayed but the loading phase lasts ~1 minute with a "No one is playing" and then, the music is loaded at 1 minute on the whole track. So I miss the first minute of the current music.

**Comment by Goutye** [comment]
The issue seems to be solved.
