### ISSUE TITLE
[Request] Disable Youtube annotations

### ISSUE THREAD

**Issue by Netox005** [dubtrack/www-dubtrack-fm#59]
They are annoying and sometimes the Youtube icon overlaps them so you can't remove them.
I found out both the annotations and the Youtube logo are HTML elements so you can remove them easly.

**Comment by zewm** [comment]
A temporary work-around is to log in to your youtube account and disable annotations by default in your user settings. Of course this will also disable them outside of dubtrack but it's a start.

**Comment by nambok** [comment]
this is now done
