### ISSUE TITLE
:elephant::dash: emoji support

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#6]
:elephant::dash: does not work in chat.  how am i supposed to fart like an elephant?

**Comment by andrewtibbetts** [comment]
+1

**Comment by scytheria1001** [comment]
+1111111

**Comment by minustime** [comment]
Can these widely used emoji definitions be integrated on a future iteration of the site? http://www.emoji-cheat-sheet.com

**Comment by nambok** [comment]
I 100% agree with this, @minustime ill integrate all of those over the weekend. A bit difficult to get work done during the week

**Comment by scytheria1001** [comment]
can we get some help with finding emojis too? like start typing and have suggestions, like it does here?

:wave:

**Comment by nambok** [comment]
all this emojis were added http://www.emoji-cheat-sheet.com/ :elephant::dash:  as much as you like on dubtrack. Closing this for now but feel free to re-open
