### ISSUE TITLE
Some images not loaded via SSL

### ISSUE THREAD

**Issue by Plazmaz** [dubtrack/www-dubtrack-fm#62]
Images are often loaded via http://* vs https://* when served from images.dubtrack.fm. this is of low concern, but it does cause the chrome dev console to spit out a ton of warnings. An example of this:
http://images.dubtrack.fm/hhberclba/image/upload/c_fill,h_200,w_200/ryv37uqhlrxupsxjtpqx.jpg

**Comment by nambok** [comment]
this is now fixed
