### ISSUE TITLE
Hide Video Button always showing

### ISSUE THREAD

**Issue by OriginNRG** [dubtrack/www-dubtrack-fm#63]
The hide video button always displays over the video whilst the other options hide. 

Element in question:
> #main_player .player_container .hideVideo-el

Needs to `display:block` when you :hover on element:
> .html5-video-container

**Comment by Leykis** [comment]
It seems this option has completely disappeared all together now :(

**Comment by coryshaw1** [comment]
Hiding an embedded YouTube video is against YouTube's ToS

**Comment by nambok** [comment]
this is now fixed
