### ISSUE TITLE
next track in queue not loading

### ISSUE THREAD

**Issue by parkeerwacht** [dubtrack/www-dubtrack-fm#66]
Apparently all rooms are having this issue for me where the next track isn`t being loaded.

**Comment by WiBla** [comment]
I confirm.

**Comment by aemxdp** [comment]
:+1:

**Comment by zurbo** [comment]
:+1:

**Comment by ProDjMx** [comment]
:+1:

**Comment by aemixdp** [comment]
Again :disappointed:

**Comment by zurbo** [comment]
It works for everyone in french EDM community

**Comment by aemixdp** [comment]
It seems everything's ok again globally.

**Comment by nambok** [comment]
this is now fixed :), we reworked the entire queue system and now mods can even reorder the room queue.

closing for now, feel free to reopen the ticket
