### ISSUE TITLE
IP and User-Agent disclosure via embedded images

### ISSUE THREAD

**Issue by Plazmaz** [dubtrack/www-dubtrack-fm#67]
Unfortunately, I was unable to report this to you privately as there's no existing venue for this, but images pasted into chat are linked directly via the src attribute of the image tag, which allows for the retrieval of information about all users in any given room using a tracking pixel. Essentially, a php script can be created to serve png images, and grab the all headers sent by the browser, and the image can then be linked within any dubtrack.fm chat. 

The php script will then be sent a request by all users in the room without user confirmation. A good way to mitigate this is using an image proxy, where every image is retrieved, uploaded to dubtrack.fm's servers, and then served to the client from https://images.dubtrack.fm.

**Comment by nambok** [comment]
unfortunately uploading images to chat will probably create too much costs for us and create extra load. For the moment I think the best is to whitelist images that get loaded on the chat: 7f9120197400bdcdc1c6c61ce80dd395e0a273a5. Feel free to add whatever domains you think are safe for load. Closing this for now
