### ISSUE TITLE
No image size limitation on embedded images

### ISSUE THREAD

**Issue by Plazmaz** [dubtrack/www-dubtrack-fm#68]
This could be resolved using the same fix as #67, essentially, users can send immensely large images such as http://www.thewallpapers.org/photo/76170/3-2-Rocky_Beach.jpg and bring the browser of all other users to a screeching halt. Though the image can be downscaled via #42, the actual image is still loaded in full, and then shrunk via css.

**Comment by nambok** [comment]
this is now done

**Comment by nambok** [comment]
fixed with 7f9120197400bdcdc1c6c61ce80dd395e0a273a5. whitelisted domains to display images on chat

**Comment by JTBrinkmann** [comment]
from the imgur help:

> The maximum file size for non-animated images is 20MB. The maximum file size for GIFs is 200MB

(for comparison: the Rocky_Beach.jpg one plazmaz linked is 16.48MB)
