### ISSUE TITLE
[Feature request] Controls within Playlist listing (Add to playlist, Move to top)

### ISSUE THREAD

**Issue by ydrecords** [dubtrack/www-dubtrack-fm#69]
When viewing the contents of a playlist, available controls for each track are "Add to queue" and "Delete".

- Adding a "(+) Playlist" button, similar to the one in search listing, would make it possible to copy or move tracks between playlists.

- A " ^ Move to top" button for each track in this playlist listing, similar to the one in My Queue listing, would also help reorder songs in a playlist.

- When viewing contents of a playlist, it would be nice to see the number of songs in the playlist displayed at top.

**Comment by nambok** [comment]
part of this is done, will complete this week

**Comment by jsmoro** [comment]
It would be nice to have the drag'n'drop between playlists, but the "heart" (+) button do the job ;-)
