### ISSUE TITLE
Video doesn't change and constantly repeats

### ISSUE THREAD

**Issue by dsdude123** [dubtrack/www-dubtrack-fm#74]
Ever since late last week, videos have been getting stuck and repeating. 
The JavaScript console reports the following:

19:57:11.847 TypeError: K is null1 provider.youtube.js:1:4688

19:57:13.355 Error: Permission denied to access property "toString"1 www-embed-player-new.js:103:64

19:59:20.860 TypeError: I is null1 provider.youtube.js:1:1734

**Comment by nambok** [comment]
is anyone else getting this issue?

@dsdude123 what browser are you on?

**Comment by dsdude123** [comment]
Firefox, others in the room have the same issue, it seems to only occur on one persons videos. One night my videos were causing the issue and the tonight it was someone else. There occasionally is other side effects like the chat box becoming unresponsive

**Comment by nambok** [comment]
this is really odd, i will look into this and let you know if I can find a fix for it

**Comment by nambok** [comment]
ok this should be fixed, feel free to repoen
