### ISSUE TITLE
playlist prominence and functionality

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#8]
queue and playlists need a higher prominence and more functionality in the design of the site.  

1) playlists should be view-able and edit-able in reduced screen "mini-mode".  "room queue", "my queue", and "my playlists" should all be clearly defined. 
2) "room queue" needs to be much more clearly defined and immediately recognized as *this is what is playing and what is going to play in here* - right now it is buried and nobody knows that is coming up next. the play button should default on "room queue" and should be clear graphically that this is what is playing, and going to play in the room.  current song playing should have a clear separation and prominence.
3) under the "playlists" button, default on "my queue" as it currently does. make it clear graphically that is not what is playing but what you want to play in the room. also have a tab for "my playlists".  everything should have full edit functionality in the mini-mode panel.
4) *important* we need to be able to add and move songs to the top, shuffle, and add and move songs to the bottom of playlists. this also applies to "my queue" - i'd like to emphasize the "add to top/bottom of queue" options.
5) create a means for users to start and stop djing aside from having songs in "my queue" - just because you are in the room doesn't mean you want to play your music at that moment. if you add a 200 song playlist to "my queue" you aren't going to delete each song individually to stop djing
6) create a "clear queue" button for users to clear all from "my queue"
7) create a "clear queue" button for room creators to clear all from "room queue"
8) multiple users have "added to room queue" thinking they were adding to "my queue", surprised to find they had automatically started djing. this should be more intuitive.
9) the numerical indicator on the playlist button on the bottom left is confusing because current web design standards indicate that you, the user, have X things to take care of, when actually, it's how many songs are left until you play your song. there is a lot of confusion over this indicator and what it means.

**Comment by andrewtibbetts** [comment]
+1 +1 +1 +1 +1 +1 +1 +1 +1 but should be 9 separate issues. Then we of little knowledge of the main workings can pick off little things so creators can focus on big stuff.

**Comment by nambok** [comment]
@andrewtibbetts agreed we can also turn it onto checklists, @chrisrohn I might need design help with some of this points if you know anyone that can help

**Comment by andrewtibbetts** [comment]
<— ready to help!

**Comment by nambok** [comment]
@andrewtibbetts nice! yeah if you could help re-designing that playlists/queue browser view it will be amazing!

**Comment by Leykis** [comment]
Could we please add to the list, an option to rename playlist?
Also, it seems "Shuffle playlist" was closed but I am not seeing this option?

**Comment by nambok** [comment]
all this was added on the redesign, and @Leykis you should be able to rename your playlists now
