### ISSUE TITLE
dubtrack logo on top center doesnt match dubtrack logo everywhere else

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#82]
change dubtrack top center logo to match the brand

**Comment by scytheria1001** [comment]
+1

**Comment by pootato** [comment]
the top center logo is the new logo

**Comment by chrisrohn** [comment]
@pootato but its not.

![12038330_829724160479429_5680151078095778976_n](https://cloud.githubusercontent.com/assets/11859955/10484307/706576f8-7252-11e5-8921-ac426d6e846e.jpg)

this is the logo typically used across the entire brand, everywhere except the top center of each room. this is the logo that should be on display for everyone using the site day-to-day.

**Comment by pootato** [comment]
oh I get it, they're waiting for the new design to change the logo.

**Comment by Larry1123** [comment]
This is not longer valid.
