### ISSUE TITLE
user names have no character max

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#83]
![capture](https://cloud.githubusercontent.com/assets/11859955/10321003/666a2d7e-6c44-11e5-9b77-4aa69c1ece26.PNG)

this creates problems in chat in particular.

**Comment by chrisrohn** [comment]
![capture](https://cloud.githubusercontent.com/assets/11859955/10321078/d2a9fe88-6c44-11e5-986b-7d4876f852cc.PNG)

**Comment by chrisrohn** [comment]
![capture3](https://cloud.githubusercontent.com/assets/11859955/10321250/ac213410-6c45-11e5-8932-33d0a6342a37.PNG)

![capture](https://cloud.githubusercontent.com/assets/11859955/10321255/b0afae4e-6c45-11e5-9c4e-2952ece527b2.PNG)

actually, there appears to be no limit.

**Comment by nambok** [comment]
thanks this is now fixed
