### ISSUE TITLE
Room Chat connected users list

### ISSUE THREAD

**Issue by jsmoro** [dubtrack/www-dubtrack-fm#85]
the chat users icon displays all rooms users, not only the connected ones.

**Comment by aemixdp** [comment]
Ghosts were fixed few days ago, but it seems that was a partial solution and users still become ghosts after leaving the site in certain occurrences (maybe if they vote for current track and leave, but I'm not sure).

**Comment by nambok** [comment]
this is now fixed

**Comment by jsmoro** [comment]
thx ;)
