### ISSUE TITLE
User_popover doesn't display right on mobile mode

### ISSUE THREAD

**Issue by WiBla** [dubtrack/www-dubtrack-fm#86]
One image is worth a thousands words:
![2015-10-07_12-32-39](https://cloud.githubusercontent.com/assets/11421812/10335222/9650aa1c-6cef-11e5-9701-9d12914955c7.png)
With or without my extension of course.
![2015-10-07_12-34-49](https://cloud.githubusercontent.com/assets/11421812/10335253/c4023804-6cef-11e5-965f-d58051949e8e.png)

**Comment by chrisrohn** [comment]
+1

**Comment by Larry1123** [comment]
This is no longer valid.
