### ISSUE TITLE
Queue cycle

### ISSUE THREAD

**Issue by aemixdp** [dubtrack/www-dubtrack-fm#87]
Consider the following: users A and B are sitting at the same room. User A starts DJing and puts few songs to his queue. In the middle of the first song user B enters DJ queue as well. The problem is that he is being added to the queue after the next song of user A, not after the current. My guess the better mechanics would be to make users re-enter the queue at the end of their current track's playback, not at the beginning.

**Comment by Larry1123** [comment]
#221 explains this better and has a larger discussion. Move anything new to that one.
