### ISSUE TITLE
character limits in chat

### ISSUE THREAD

**Issue by chrisrohn** [dubtrack/www-dubtrack-fm#9]
there is currently a 140 character limit in what is posted in chat, but the text box doesn't limit the number of characters you can enter into it.

the full message will post for the user who wrote it, but everyone else sees a truncated message. the message author will not know it was truncated unless another person in the room tells them.

**Comment by scytheria1001** [comment]
+1

**Comment by rklados** [comment]
plusone

**Comment by nambok** [comment]
this is now fixed

**Comment by rklados** [comment]
+infinity!  You are killing it, nambok.  Thank you for all the work!
