### ISSUE TITLE
Some Youtube videos cannot be imported

### ISSUE THREAD

**Issue by jsmoro** [dubtrack/www-dubtrack-fm#91]
Some youtube videos cannot be imported in dubtrack, maybe linked to video format?

here is a list of youtube videos not processed by dubtrack:
https://youtu.be/_U1RXcqtJ2Y
https://youtu.be/eGLcT1GaYrU
https://youtu.be/01Pomn60WxU
https://youtu.be/eIG2Zsn6W8M

**Comment by jsmoro** [comment]
https://youtu.be/01Pomn60WxU

**Comment by jsmoro** [comment]
more urls :
https://www.youtube.com/watch?v=GKQTEXWWtdQ
https://youtu.be/I02SUo7y1uc

**Comment by jsmoro** [comment]
the dubtrack API returns no data, 
e.g.
https://api.dubtrack.fm/song?name=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DI02SUo7y1uc&type=youtube

I cant find it in the repository, is the dubtrack API open source?

**Comment by SukaNekoto** [comment]
It seems that all those videos you linked either are blocked due to copyright by WMG or blocked from a certain country, which may be why dubtrack is not registering those videos.

**Comment by nambok** [comment]
yeah unfortunately those videos cant be embedded, we use the `videoEmbeddable` option when fetching videos from youtube.

**Comment by jsmoro** [comment]
it is strange, for example this video 
https://youtu.be/vJN880zWfpQ?list=PL9wDNu3ZrVQ5nbsScXvXqCIpgPCjOOEj0
can be played outside of youtube in this website
http://www.novaplanet.com/novamag/47937/le-nova-club-de-l-ete-par-david-blot

Unfortunately I didnt find a way to have the videoEmbeddable flag for a single video :(

**Comment by jsmoro** [comment]
It is possible to import those videos with the "Import Playlist" feature :-)
(but needs to create temporary YT playlist)
